reader:
  file:
    folder: file

writer:
  file:
    folder: file

excel:
  config:
    vent:
      sheet: 0
      source: 3
      sourceType: 4
      target: 9
      targetType: 5
      nullable: 6
      transformType: 7
      transformValue: 8
